// TODO Implement this library.// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZUgtKnsuW34Wz8xSolNWPOJd4wJw4E38',
    appId: '1:1021364345875:web:ace993feb84891715fb3e6',
    messagingSenderId: '1021364345875',
    projectId: 'breakingbad-97b4e',
    authDomain: 'breakingbad-97b4e.firebaseapp.com',
    storageBucket: 'breakingbad-97b4e.appspot.com',
    measurementId: 'G-LM7D2G6V5E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo93sJtV0XuardERdpRO_hMWDLi7A7-fo',
    appId: '1:1021364345875:android:eb645c6ac0987c0b5fb3e6',
    messagingSenderId: '1021364345875',
    projectId: 'breakingbad-97b4e',
    storageBucket: 'breakingbad-97b4e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxdaEhTf6x7kpBzxB1PIWKkc8Z_dFeDmc',
    appId: '1:1021364345875:ios:5c0b3a904f8f984b5fb3e6',
    messagingSenderId: '1021364345875',
    projectId: 'breakingbad-97b4e',
    storageBucket: 'breakingbad-97b4e.appspot.com',
    iosBundleId: 'com.breaking.bad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxdaEhTf6x7kpBzxB1PIWKkc8Z_dFeDmc',
    appId: '1:1021364345875:ios:fb14027e5b349ae95fb3e6',
    messagingSenderId: '1021364345875',
    projectId: 'breakingbad-97b4e',
    storageBucket: 'breakingbad-97b4e.appspot.com',
    iosBundleId: 'com.breaking.bad.stage.RunnerTests',
  );
}
